### ISSUE TITLE
hello,why the config.py doesn't work

### ISSUE THREAD

**Issue by goxofy** [Astalaseven/twitter-rss#14]
hello, i run the project on my vps, and i changed the server to "localhost:9834", but when i run the "run.py", the screen says "Running on http://0.0.0.0:5000/"

i dont know why..

thx!

**Comment by Astalaseven** [comment]
The `SERVER = 'localhost:5000'` option in `config.py` is only used to have a valid RSS feed.
If you want to change the port, you need to edit `server.py`:

```
if __name__ == "__main__":
    # app.run(debug=True)
    app.run(host='0.0.0.0')
    # app.run()
```

to

```
if __name__ == "__main__":
    app.run(your-public-ip, chosen-port)
```

like `app.run(8.8.8.8, 80)`

I hope this will help you,

**Comment by goxofy** [comment]
ooooh！！now i know,  thank you very much!!!

**Comment by goxofy** [comment]
hello, i changed the server.py , but i cant run

  File "/home/tink/twitter-rss/server.py", line 87
    app.run(67.186.23.58,9384)
                     ^
SyntaxError: invalid syntax

**Comment by Astalaseven** [comment]
My bad. Try `app.run(host='67.186.23.58', 9384)` instead.

**Comment by goxofy** [comment]
this method is also wrong....

can u help me download my twitter xml file?

else

why it always say "File could not be read"

**Comment by Astalaseven** [comment]
After a quick look in Flask doc: `app.run(host='0.0.0.0', port=9384)`
