### ISSUE TITLE
Old tweets delivered from cache, new ones never grabbed (regression)

### ISSUE THREAD

**Issue by ivan** [Astalaseven/twitter-rss#17]
I'm seeing only old cached tweets again.  This is what is going on:

After running

```
    if path == 'user':
        url = "https://mobile.twitter.com/{0}"
    else:
        url = "https://mobile.twitter.com/search?q=%23{0}"
    content = requests.get(url.format(feed))
    content = content.text.encode('utf-8')
```

the content I get is

```
Forbidden (Rate Limit Exceeded)
```

which causes `find_new_first_id` to return `42`. I then see `if new_first_id == old_first_id:` in `check_if_new_tweet` comparing `42` to `42` and always returning `False`.

If I work around this by making `check_if_new_tweet` return `True` all the time, I see new tweets.

**Comment by ivan** [comment]
If you're interested in caching tweets to prevent clients from being able to make a twitter-rss server DoS twitter and get the server blocked, you might want to go with caching tweets for a short period, say 15 minutes.  You can check if the mtime of the cached file is older than 15 minutes.  If you want a more flexible interval, you can do some math based on how frequently tweets are posted to the account or hashtag.

Note that a user could still make a public twitter-rss DoS twitter by looking up tons of new usernames or hashtags.  This could be mitigated somewhat by having a per-IP limit on the number of new usernames/hashtags.

**Comment by Astalaseven** [comment]
https://github.com/Astalaseven/twitter-rss/commit/e1b2c80d87e333ba82f6f3eb7185e4f2b19dbeff should resolve the problem.
