### ISSUE TITLE
is there example runnning server?

### ISSUE THREAD

**Issue by yunchiri** [Astalaseven/twitter-rss#2]
Thanks you!! Good job!

**Comment by Astalaseven** [comment]
There is no example server running yet, for testing I launch it in localhost. If somebody does have a server that can handle it, it would be great to propose it as a service, but I can't afford it. 

Thank you for your feedback!

**Comment by yunchiri** [comment]
When Install 

> sudo apt-get install python-pip

this error ... sorry python is firstime for me...ㅠㅠ
and i did sudo-apt update 
after also error

WARNING: The following packages cannot be authenticated!
  python-pkg-resources python-setuptools python-pip
Install these packages without verification [y/N]? y
Err http://kr.archive.ubuntu.com/ubuntu/ natty/main python-pkg-resources all 0.6.15-1ubuntu1
  404  Not Found
Err http://kr.archive.ubuntu.com/ubuntu/ natty/main python-setuptools all 0.6.15-1ubuntu1
  404  Not Found
Err http://kr.archive.ubuntu.com/ubuntu/ natty/universe python-pip all 0.8.2-0ubuntu1
  404  Not Found
Failed to fetch http://kr.archive.ubuntu.com/ubuntu/pool/main/d/distribute/python-pkg-resources_0.6.15-1ubuntu1_all.deb  404  Not Found
Failed to fetch http://kr.archive.ubuntu.com/ubuntu/pool/main/d/distribute/python-setuptools_0.6.15-1ubuntu1_all.deb  404  Not Found
Failed to fetch http://kr.archive.ubuntu.com/ubuntu/pool/universe/p/python-pip/python-pip_0.8.2-0ubuntu1_all.deb  404  Not Found
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by Astalaseven** [comment]
The problem is the packages are not found on the server. You can try to
change them : https://help.ubuntu.com/community/Repositories/Ubuntu
It is an Ubuntu problem, not a python one :)

**Comment by yunchiri** [comment]
Thank you, i installed ubuntu 12.04 instead 11.04 , now installed all ...

Thank you feedback and get sorry  i got the problem too

=>
I edited config.py

SERVER = '14.63.221.251:80'
DIR = '/usr/local/twitter-rss/'
#DIR = '/var/www/twitter-rss/' # must exist and must have right to read/write
PICS = False
~  
~                    

after run with command

sudo python2 run.py

Updating ALL THE FEEDS!
File could not be read
- Running on http://127.0.0.1:5000/
- Restarting with reloader

> > question

this message
config.py didn't be accept?

**Comment by Astalaseven** [comment]
I forgot to change back 

```
if __name__ == "__main__":
    app.run(debug=True)
    # app.run(host='0.0.0.0')
    # app.run()
```

to

```
if __name__ == "__main__":
    # app.run(debug=True)
    app.run(host='0.0.0.0')
    # app.run()
```

in the `server.py` file.

But, if you want to change the default port, you will need to use:

```
app.run(14.63.221.251, 80) 
```

and comment all the other ones.

To use port 80, you will need the root (`sudo`) rights, otherwise, with port 5000, you don't need them.
And `Running on http://127.0.0.1:5000/` should be `Running on http://14.63.221.251:80/` then.
(I tested it in localhost)

**Comment by yunchiri** [comment]
edited 

if **name** == "**main**":
    # app.run(debug=True)
    app.run(14.63.221.251, 80)
    # app.run()

->

root@32957485-95b5-4ab5-b548-5270884f8dc3:/var/www/twitter-rss# sudo python2 run.py
Updating ALL THE FEEDS!
File could not be read
  File "server.py", line 86
    app.run(14.63.221.251, 80)
                    ^
SyntaxError: invalid syntax

sorry i didn't phyton so i can't solve
can you give me advise?

**Comment by Astalaseven** [comment]
One first advice: Don't run it as root!

In your edit I don't see any indentation, are you sure they are 4 spaces before `app.run(14.63.221.251, 80)` ? Indentation is very important in Python.

**Comment by yunchiri** [comment]
Thank you feedback 
I tried but fail... sorry as newbie  ㅠㅠ

[edited by Asta]

despite keep 4 space rule but
same error
Really really sorry 

File could not be read
  File "server.py", line 88
    app.run(14.63.221.251, 80)

and

config didn't change

**Comment by Astalaseven** [comment]
Ok, I edited your comment. It's not a good idea to launch a program as root when not needed, but sending his server login is not better :).

I'll try to launch it on your server.

**Comment by Astalaseven** [comment]
I cloned my repo on your server and launched `run.py` from there. On the server side, it works. But I don't have any response from my browser ?! Can you try to check http://14.63.221.251:5000/ ? 

I don't know if this is censorship or blocked ports on your server, but it's strange...

**Comment by yunchiri** [comment]
Oh i forgot port forwarding

now it avable!

 i will try!

**Comment by yunchiri** [comment]
GOOD JOB! working done

can you tell me what i mistake before?

**Comment by Astalaseven** [comment]
It works also on my side. You will need to create a directory to save
the files, I cannot do it :)

I closed the program, you can relaunch it by going to the `twit/` folder and launching `python2 run.py`. 
Do it in a screen, otherwise the program will close if your connection is lost.

https://help.ubuntu.com/community/Screen

**Comment by yunchiri** [comment]
Thank you! make a understand
