### ISSUE TITLE
Add an automated Docker build on the Docker hub registry  

### ISSUE THREAD

**Issue by djmaze** [Astalaseven/twitter-rss#22]
Hi @Astalaseven, I created a so called [automated build](http://docs.docker.com/docker-hub/builds/) for twitter-rss some time ago. You can find it [here](https://registry.hub.docker.com/u/mazzolino/twitter-rss/). It automatically builds a new docker image as soon as a change in the source repository is pushed. People can just a `docker pull ..` (and then `docker run..`) and get it running on their machines, without installing or compiling anything.

I had to make a fork of this repository, as I can only add automated builds for my own repositories. Someone already complained about my outdated build. It would be even better if your main repository would be available as a build as well, so I don't have to update my fork every time there is a change in this repository.

So. if you like, you could register a free account at the Docker hub and add this repository as an automated build. It is quite easy, see the [documentation](http://docs.docker.com/docker-hub/builds/). You might possibly have to set up a webhook manually. It will tell you if that is the case.

Afterwards, you will have automated Docker builds for every push made on the master branch. Cool, huh?

**Comment by Astalaseven** [comment]
Should be done :)

https://registry.hub.docker.com/u/astalaseven/twitter-rss/

**Comment by djmaze** [comment]
Great, thx for the effort!
