### ISSUE TITLE
User feeds are empty

### ISSUE THREAD

**Issue by djmaze** [Astalaseven/twitter-rss#23]
Since quite some time, all user feeds are empty for me. The returned xml returns only the general `<channel>` tag but no posts. Interestingly, the tag `<language>` inside the channel is always set to `fr` for me.

Did Twitter change output again? Seems an update to the parser is needed.

**Comment by Astalaseven** [comment]
Do you use the latest version? I tried it a few minutes earlier and it worked well.

Perhaps you try to parse new feeds, jparyani sent a pull https://github.com/Astalaseven/twitter-rss/pull/20 and it has been merged.

**Comment by djmaze** [comment]
Yes, but I updated the wrong server. Shame on me. Sorry for the noise, it works!

**Comment by Astalaseven** [comment]
No problem, good to know it works!
