### ISSUE TITLE
Broken pipe

### ISSUE THREAD

**Issue by ghost** [Astalaseven/twitter-rss#24]
any idea what causes this?

```
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 46714)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 657, in __init__
    self.finish()
  File "/usr/local/lib/python2.7/SocketServer.py", line 716, in finish
    self.wfile.close()
  File "/usr/local/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/local/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
```

**Comment by Astalaseven** [comment]
It looks like a lowlevel system problem: http://stackoverflow.com/questions/11866792/how-to-prevent-errno-32-broken-pipe

Perhaps a problem with a timeout, does it happen often?

**Comment by ghost** [comment]
yeah, at every checkout, maybe its my client  (seamonkey mail & news Feeds) quitting too soon

**Comment by ghost** [comment]
it seems to be related to having pictures = True

maybe something in the stream makes the client choke? is that image data escaped properly?

**Comment by ghost** [comment]
tracked it down to some maximum wait timeout in
comm-release/mailnews/extensions/newsblog/content/FeedUtils.jsm

// Timeout for nonresponse to request, 30 seconds.
  REQUEST_TIMEOUT: 90 \* 1000,

had to up it vastly, 30s isn't enough to get through 
http://localhost:5000/user/HistoryTime_.xml

for some reason your program iterates through all uris in the tweets and does lookups? at a rate of 1 per second, that takes forever, is this to resolve shorteners or why?

...
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): twitter.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): twitter.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): pic.twitter.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): twitter.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): twitter.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): pic.twitter.com
...
